# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cityflagtestios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.7'

  # Pods for cityflagtestios

  target 'cityflagtestiosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cityflagtestiosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
